### ISSUE TITLE
请正确标明文章引用

### ISSUE THREAD

**Issue by zxl19** [yuanzhuangkafei/yuanzhuangkafei.github.io#3]
你好，你于**2022年5月27日**发表的博客[Awesome-list](http://coffeelize.top/posts/1ea487ce.html)中的内容与我**2021年5月31日**发表的博客[高质量Awesome List存档](https://zxl19.github.io/awesome-list/)中的内容完全相同，请正确标明文章引用，谢谢！

**Comment by yuanzhuangkafei** [comment]
好的，已收到，今天之内我会及时处理



---原始邮件---
发件人: "Lucas ***@***.***&gt;
发送时间: 2022年5月28日(周六) 中午12:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yuanzhuangkafei/yuanzhuangkafei.github.io] 请正确标明文章引用 (Issue #3)




 
你好，你于2022年5月27日发表的博客Awesome-list中的内容与我2021年5月31日发表的博客高质量Awesome List存档中的内容完全相同，请正确标明文章引用，谢谢！
